# screener_config.py

CSP_SCORE_THRESHOLD = 20
ROC_THRESHOLD = 1.5  # %
MIN_DELTA = 0.2
MAX_DELTA = 0.45
DELTA_RANGE = (0.2, 0.45)  # Using a tuple
MIN_OI = 100
MIN_PREMIUM = 0.25
MIN_ROC = 0.24
MAX_EXPIRATION_DAYS = 30
MIN_OTM_PCT = 2.0
ROC_LOOKBACK_DAYS = 10
OPTION_LIMIT_PER_TICKER = 2
INCLUDE_NEAR_MISS = True
